import mongoose from "mongoose";

const historialPacienteSchema = new mongoose.Schema({

    identificadorPaciente: { type: String, required: true },
    idHistorial: { type: String, required: true },
    antecedentesFamiliares: { type: [String], default: [] },
    antecedentesMedicos: { type: [String], default: [] },
    antecedentesQuirurgicos: { type: String, default: "" },
    motivoConsulta: { type: String, required: true },
    fechaEvaluacion: { type: Date, default: Date.now },
    duracionPlan: { type: String, default: "" },
    frecuenciaSesiones: { type: String, default: "" },
    habitosDeEjercicio: { type: [String], default: [] },
    consentimientoInformado: { type: String, default: "Sí" },
    intervencionesPrevias: { type: String, default: "No" },
    cualesIntervenciones: { type: [String], default: [] },
    medicacionActual: { type: String, default: "Ninguna" },
    objetivoCortoPlazo: { type: String, default: "" },
    obserExploraciones: { type: String, default: "" },
    pruebasEspeciales: { type: String, default: "No" }, 
    cualesPruebasEspeciales: { type: [String], default: [] },
    resultadoPruebas: { type: String, default: "" },
    observacionesHistorial: { type: String, default: "" },
    fechaNacimiento: { type: String, default: "" },
    sexo: { type: String, default: "" },
    talla: { type: String, default: "" },
    peso: { type: String, default: "" },
    direccion: { type: String, default: "" },
    ocupacion: { type: String, default: "" },
    correoElectronico: { type: String, default: "" },
    eva: { type: String, default: "" },
    dolor24hrs: { type: String, default: "" },
    tipo: { type: String, default: "" },
    facModifica: { type: String, default: "" },
    sensacion: { type: String, default: "" },
    anioQuirurgico: { type: String, default: "" },
    diagnosticoMedico: { type: String, default: "" },
    indicacionesMedicas: { type: String, default: "" },
    dolorPalpacion: { type: String, default: "" },
    espasmoPalpacion: { type: String, default: "" },
    antecedentesNoPatologicos: { type: Object, default: {} },
    lesiones: { type: Object, default: {} },
    obser: { type: Object, default: {} },
    soapFK: { type: mongoose.Schema.Types.ObjectId, ref: "Nota" },
});

export default mongoose.model("HistorialPacientes", historialPacienteSchema);
